OfinaVirtual_VSS/OficinaVirtual.Cliente.WebApp/Controllers/OrientacionController.cs
using OficinaVirtual.Entidad.Consulta;
using OficinaVirtual.Fachada.Consulta;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace OficinaVirtual.Cliente.WebApp.Controllers
{
    public class OrientacionController : Controller
    {
        // GET: Orientacion
        public async Task<ActionResult> Index()
        {
            clsListaOrientacion oDatos = new clsListaOrientacion();

            try
            {
                oDatos = await clsOrientacion.ListarOrientacion();
            }
            catch
            {
                throw;
            }

            return View(oDatos);
        }

        public async Task<ActionResult> _Requisitos(int IdTipoOrientacion)
        {
            clsParametroConsulta oParametro = new clsParametroConsulta();
            clsListaRequisitos oDatos = new clsListaRequisitos();

            try
            {
                oParametro.ParametroControlTag = $"IdTipoOrientacion|{IdTipoOrientacion}";
                oDatos = await clsOrientacion.RequisitosXOrientacion(oParametro);
            }
            catch
            {
                throw;
            }

            return PartialView(oDatos);
        }

        public async Task<ActionResult> DecretoUrgencia035()
        {
            return View();
        }

        public async Task<ActionResult> BeneficiarioPreguntas()
        {
            return View();
        }

        public async Task<ActionResult> Tema(String id)
        {
            var v = ViewEngines.Engines.FindView(this.ControllerContext, id, null);

            if (v.View == null) return View();

            return View(id);
        }
    }
}

OfinaVirtual_VSS/OficinaVirtual.Cliente.WebApp/Controllers/SuministroEmpresaController.cs
using Newtonsoft.Json.Linq;
using OficinaVirtual.Entidad.Consulta;
using OficinaVirtual.Fachada.Consulta;
using OficinaVirtual.Util.Tool;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Data;
using System.IO.Compression;
using System.Web.Script.Serialization;

namespace OficinaVirtual.Cliente.WebApp.Controllers
{
    public class SuministroEmpresaController : Controller
    {
        #region Fields

        private static readonly clsConvert _Convert = clsConvert.Instancia;
        private static readonly String _TokenDistriluz = ConfigurationManager.AppSettings["TokenDistriluz"];
        private static Random random = new Random();
        #endregion Fields

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> ResumenDeudas()
        {

            Session.Remove("TransactionToken");
            Session.Remove("CustomerEmail");
            Session.Remove("IdEmpresa");
            Session.Remove("NroPedido");
            Session.Remove("SessionKey");
            Session.Remove("Monto");
            Session.Remove("SessionToken");

            if (Session["IdUsuario"] != null)
            {
                try
                {
                    clsParametro param = new clsParametro();
                    param.Parametros = new Dictionary<String, String>();
                    var oTarifa = await clsAccountEmpresa.ListarTarifaActiva(param);

                    if (oTarifa.IdError == 0)
                    {
                        var oRolesResult = _Convert.ToJson(oTarifa.Datos);
                        JArray oRolesResultParse = JArray.Parse(oRolesResult);

                        ViewBag.Tarifa = oRolesResultParse;
                        ViewBag.VisaURLButtonJS = await clsVisa.GetVisaURLButtonJS(0);

                        return View();

                    }
                    else
                    {
                        ViewBag.Mensaje = "Se produjo un error al cargar el resumen de deudas.";
                        return View();
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = "Se produjo un error al cargar el resumen de deudas.";
                    ViewBag.Exito = false;
                    return View();
                }
            }

            else
            {
                return RedirectToAction("Login", "AccountEmpresa");
            }

        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> ListarSuministroEmpresa(string suministro, string tarifa, string empresadistriluz)
        {
            if (Session["IdUsuario"] != null)
            {

                try
                {

                    ViewBag.Global = Session["Global"];
                    string ruc = "";

                    foreach (var item in ViewBag.Global.LoginAcceso)
                    {
                        if (item.Key == "ruc")
                        {
                            ruc = item.Value;
                        }
                    }

                    if (tarifa == "") tarifa = "0";

                    clsParametro param = new clsParametro();
                    param.Parametros = new Dictionary<String, String>();
                    param.Parametros["rucempresa"] = ruc;
                    param.Parametros["empresadistriluz"] = empresadistriluz;
                    param.Parametros["suministro"] = suministro;
                    param.Parametros["tarifa"] = tarifa;

                    var oTarifa = await clsAccountEmpresa.ListarSuministros(param);

                    var result = _Convert.ToObject<List<Dictionary<String, String>>>(oTarifa.Datos.ToString());

                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(ex.Message);
                }

            }
            else
            {
                return RedirectToAction("Login", "AccountEmpresa");
            }
        }




        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> _VerDetallePagosSuministros(string suministro)
        {
            if (Session["IdUsuario"] != null)
            {

                try
            {

                clsParametro param = new clsParametro();
                param.Parametros = new Dictionary<String, String>();
                param.Parametros["suministro"] = suministro;


                var olista = await clsAccountEmpresa.ListarSuministrosDetallePago(param);

                var result = _Convert.ToObject<List<Dictionary<String, String>>>(olista.Datos.ToString());

                string vista = RenderPartialToString(this, "_VerDetallePagosSuministros", result, ViewData, TempData);

                return Json(new { Html = vista, Lista = result }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

            }
            else
            {
                return RedirectToAction("Login", "AccountEmpresa");
            }
        }





        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> EliminarSuministroEmpresa(string suministro)
        {
            if (Session["IdUsuario"] != null)
            {
                try
            {

                ViewBag.Global = Session["Global"];
                string IdUsuario = "";

                foreach (var item in ViewBag.Global.LoginAcceso)
                {
                    if (item.Key == "IdUsuario")
                    {
                        IdUsuario = item.Value;
                    }
                }

                clsParametro param = new clsParametro();
                param.Parametros = new Dictionary<String, String>();
                param.Parametros["IdUsuario"] = IdUsuario;
                param.Parametros["suministro"] = suministro;

                var oResultado = await clsAccountEmpresa.EliminarSuministroAsociado(param);

                return Json(oResultado);

            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

            }
            else
            {
                return RedirectToAction("Login", "AccountEmpresa");
            }
        }



        public static string RenderPartialToString(Controller controller, string partialViewName, object model, ViewDataDictionary viewData, TempDataDictionary tempData)
        {
            ViewEngineResult result = ViewEngines.Engines.FindPartialView(controller.ControllerContext, partialViewName);

            if (result.View != null)
            {
                controller.ViewData.Model = model;
                StringBuilder sb = new StringBuilder();
                using (StringWriter sw = new StringWriter(sb))
                {
                    using (HtmlTextWriter output = new HtmlTextWriter(sw))
                    {
                        ViewContext viewContext = new ViewContext(controller.ControllerContext, result.View, viewData, tempData, output);
                        result.View.Render(viewContext, output);
                    }
                }

                return sb.ToString();
            }

            return String.Empty;
        }




        public ActionResult _RegistrarReclamo(clsParametro param)
        {
            if (Session["IdUsuario"] != null)
            {
                ViewBag.SuminAsoci = param.Parametros["Suministro"];

                return PartialView("_RegistrarReclamo");
            }
            else
            {
                return RedirectToAction("Login", "AccountEmpresa");
            }
        }



        [AllowAnonymous]
        [HttpGet]
        public ActionResult _AgregarSuministro(string empresa)
        {
            if (Session["IdUsuario"] != null)
            { 
                clsConsultaSuministro oDatos = new clsConsultaSuministro();
                oDatos.Proveedora = empresa;
                return PartialView(oDatos);}
            else
            { return RedirectToAction("Login", "Account");}
                
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> _AgregarSuministro(clsConsultaSuministro modDatos)
        {
            if (Session["IdUsuario"] != null)
            {
                clsConsultaSuministro oDatos;
                clsParametroConsulta oParametro = new clsParametroConsulta();

                if (!ModelState.IsValid)
                {
                    modDatos.Mensaje = "val" +
                        "" +
                        "" +
                        "" +
                        "" +
                        "" +
                        "" +
                        "idar";
                    return PartialView(modDatos);
                }

                try
                {
                    StringBuilder sValores = new StringBuilder();
                    sValores.Append(string.Format("usuario|{0};", Session["UsuarioUltimo"]));
                    sValores.Append(string.Format("idnroservicio|{0};", $"{modDatos.Suministro}"));
                    sValores.Append(string.Format("nrorecibo|{0}", $"{modDatos.Recibo}"));



                    ViewBag.Global = Session["Global"];
                    string ruc = "";

                    foreach (var item in ViewBag.Global.LoginAcceso)
                    {
                        if (item.Key == "ruc")
                        {
                            ruc = item.Value;
                        }
                    }



                    oParametro.ParametroControlTag = sValores.ToString();

OfinaVirtual_VSS/OficinaVirtual.Cliente.WebApp/Views/AccountEmpresa/MenuClienteEmpresa.cshtml
@{
    ViewBag.Title = "MenuClienteEmpresa";
    string rolOpciones = "";
    string rolIconos = "";
}
<!-- Css -->
<link href="~/Content/AccountEmpresa/MenuClienteEmpresa.css" rel="stylesheet" />
<!-- Css -->
<!-- Content -->
<div class="contentSuministro">
    <article class="infoSuministro infoSuministro-ef-1">
        <form id="frmResumen" class="frmResumen" method="post" action="@Url.Action("VisaFinalizar", "Suministro")"></form>
        <input type="hidden" id="txtIdUser" value="@Session["IdUsuario"]" />
        <div class="ViewBagLoginAcceso dis-non">
            @foreach (var item in ViewBag.Global.LoginAcceso)
            {
                <div id="@item.Key">@item.Value</div>
            }
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="tituloSuministro text-center">
                    <h3>
                        <label class="green">Bienvenido a la</label><label class="lighBlue">&nbsp;Oficina Virtual - Empresas</label>
                    </h3>
                    <br>
                </div>
            </div>
           
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="row">
                    @foreach (var item in ViewBag.Global.LoginAcceso)
                    {
                        <!-- rolOpciones -->
                        if (item.Key == "rolOpciones")
                        {
                            string rol = item.Value;
                            string[] lista = rol.Split(',');
                            foreach (var valor in lista)
                            {
                                rolOpciones += valor.Trim() + "-";
                            }
                        }
                        <!-- rolOpciones -->
                        <!-- rolIconos -->
                        if (item.Key == "rolIconos")
                        {
                            string rol = item.Value;
                            string[] lista = rol.Split(',');
                            foreach (var valor in lista)
                            {
                                rolIconos += valor.Trim() + "|";
                            }
                        }
                        <!-- rolIconos -->
                        <!-- rolNombres -->
                        if (item.Key == "rolNombres")
                        {
                            string rol = item.Value;
                            string[] lista = rol.Split(',');
                            int count = 0;
                            foreach (var valor in lista)
                            {
                                string[] rolcadena = rolOpciones.Split('-');
                                string rolNombre = rolcadena[count];
                                string[] accion = rolNombre.Split('/');
                                string[] controlador = rolNombre.Split('/');
                                string[] iconcadena = rolIconos.Split('|');
                                <div class="col-lg-4 col-md-4 col-sm-4">
                                    <div class="menu-ef-1">
                                        <div class="menu-ef-1-content">
                                            <div class="menu-ef-1-icon text-center small">
                                                <span>
                                                    <a href="@(Url.Action(accion[1], controlador[0]))" class="@iconcadena[count]"></a>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="menu-ef-1-footer text-center">
                                            <a href="@(Url.Action(accion[1], controlador[0]))">@valor</a>
                                        </div>
                                    </div>
                                </div>
                                count++;
                            }
                        }
                        <!-- rolNombres -->
                    }
                </div>
            </div>
        </div>
    </article>
</div>
<!-- Content -->
<!-- Script -->
<script type="text/javascript" src="~/Scripts/Util.js"></script>
<!-- Script -->

OfinaVirtual_VSS/OficinaVirtual.Cliente.WebApp/Views/AccountEmpresa/RegistrarUsuarios.cshtml
@model OficinaVirtual.Entidad.Consulta.clsRegistrarUsuarios
@{
    var sExito = ViewBag.Exito;
    var sMensaje = ViewBag.Mensaje;
}
<!-- Css -->
<style type="text/css">
    .pass {
        -webkit-text-security: circle;
    }
</style>
<!-- Css -->
<!-- Content -->
<div class="contentActualizar">
    <article class="infoSuministro">
        @{
            if (sExito == true)
            {
                <div class="alert alert-success">
                    <div>
                        <span class="font-weight-bold"><i class="fa fa-info-circle fa-1x alert-success" aria-hidden="true"></i>&nbsp;@sMensaje</span>
                    </div>
                </div>
            }
            else
            {
                if (sMensaje != "")
                {
                    <div class="alert alert-warning">
                        <div>
                            <span class="font-weight-bold"><i class="fa fa-info-circle fa-1x alert-warning" aria-hidden="true"></i>&nbsp;@sMensaje</span>
                        </div>
                    </div>
                }
            }
            using (Html.BeginForm("RegistrarUsuarios", "AccountEmpresa", FormMethod.Post, new { @class = "oFrm form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <header>
                    <h2 class="lighBlue">Listado de altas de usuarios empresa</h2>
                </header>
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group row">
                            <div class="col-sm-12">
                                @Html.LabelFor(model => model.nombre, new { @class = "control-label" })
                            </div>
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group row">
                            <div class="col-sm-12">
                                @Html.LabelFor(model => model.correo, new { @class = "control-label" })
                            </div>
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.correo, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group row">
                            <div class="col-sm-12">
                                @Html.LabelFor(model => model.usuario, new { @class = "control-label" })
                            </div>
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.usuario, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group row">
                            <div class="col-sm-12">
                                @Html.LabelFor(model => model.estado, new { @class = "control-label" })
                            </div>
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.estado, new SelectList(
                                   new List<Object>{
                                       new { value = "", text = "Seleccionar" },
                                       new { value = "Deshabilitado", text = "Deshabilitado" },
                                       new { value = "Activo", text = "Activo"}
                                   },
                                   "value",
                                   "text",
                                   ""),
                                   new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        @*<div class="form-group row">
                                <div class="col-sm-12">
                                @Html.LabelFor(model => model.empresacliente, new { @class = "control-label" })
                                </div>
                                <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.empresacliente, new { @class = "form-control" })
                                </div>
                            </div>*@
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group row">
                            <div class="col-sm-12">
                                @Html.LabelFor(model => model.guardar, new { @class = "control-label vis-hid" })
                            </div>
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <input type="reset" class="btn btn-dark" value="Limpiar" id="btnLimpiar" />
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="button" class="btn btn-info" value="Nuevo" id="btnNuevo" onclick="location.href='@Url.Action("NuevoUsuarioEmpresa", "AccountEmpresa")'" />
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="submit" class="btn btn-secondary" value="Buscar" id="btnBuscar" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <table id="tabUsuEmp" class="table table-striped table-bordered nowrap" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Apellidos</th>
                                    <th>Usuario</th>
                                    <th>Cargo</th>
                                    <th>E. Cliente</th>
                                    <th>Estado</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.ListarClienteEmpresa)
                                {
                                    <tr>
                                        <td class="text-center">
                                            @item["Nombres"].ToString()
                                        </td>
                                        <td class="text-center">
                                            @item["ApellidoPaterno"].ToString()@Html.Raw(", ")@item["ApellidoMaterno"].ToString()
                                        </td>
                                        <td class="text-center">
                                            @item["Usuario"].ToString()
                                        </td>
                                        <td class="text-center">
                                            @item["Cargo"].ToString()
                                        </td>
                                        <td class="text-center">
                                            @item["NombreCliente"].ToString()
                                        </td>
                                        <td class="text-center">
                                            @item["Estado"].ToString()
                                        </td>
                                        <td class="text-center">
                                            <a href="@(Url.Action("EditarUsuarioEmpresa", "AccountEmpresa", new { idClienteEmpresa = @item["IdUsuarioWeb"].ToString() }))" id="aEdit_@item["IdUsuarioWeb"].ToString()" class="fas fa-edit aEdit_"></a>
                                        </td>
                                        <td class="text-center">
                                            <a href="#" id="aEli_@item["IdUsuarioWeb"].ToString()" class="far fa-trash-alt aEli_"></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            }
        }
    </article>
    <aside class="menu">
        <ul>
            <li>
                <a class="toolGreen efect" data-title="Suministros" target="_blank" href='@(Url.Action("ResumenDeudas", "SuministroEmpresa"))'>
                    <span class="ico"><i class="fa fa-file-o"></i></span>
                    <span class="info">Suministros</span>
                </a>
            </li>
            <li>
                <a class="toolGreen efect" data-title="Mantenimiento de Usuarios" target="_blank" href='@(Url.Action("RegistrarUsuarios", "AccountEmpresa"))'>
                    <span class="ico"><i class="fa fa-user-o"></i></span>
                    <span class="info">Mantenimiento de Usuarios</span>
                </a>
            </li>
            <li>
                <a class="toolGreen efect" data-title="Tramites" target="_blank" href='@(Url.Action("Index", "Orientacion"))'>
                    <span class="ico"><i class="fa fa-file-text-o"></i></span>
                    <span class="info">Tramites</span>
                </a>
            </li>
            <li>
                <a class="toolGreen efect" data-title="Reclamos" target="_blank" href='@(Url.Action("Reclamo", "Suministro"))'>
                    <span class="ico"><i class="fa fa-comment-o"></i></span>
                    <span class="info">Reclamos</span>
                </a>
            </li>
            <li>
                <a class="toolGreen efect" data-title="Contáctanos" target="_blank" href='@(Url.Action("Contactenos", "Home"))'>
                    <span class="ico"><i class="fa fa-phone-volume"></i></span>
                    <span class="info">Contáctanos</span>
                </a>
            </li>
            <li>
                <a class="toolGreen efect" data-title="Lugares de Pago" target="_blank" href='@(Url.Action("LugaresPago", "Home"))'>
                    <span class="ico"><i class="fa fa-map-o"></i></span>
                    <span class="info">Lugares de Pago</span>
                </a>
            </li>
        </ul>
    </aside>

</div>
<!-- Content -->
<!-- Script -->
<script type="text/javascript" src="~/Scripts/AccountEmpresa/RegistrarUsuarios.js"></script>
<!-- Script -->

OfinaVirtual_VSS/OficinaVirtual.Cliente.WebApp/Views/AccountEmpresa/_Logout.cshtml
@using (Html.BeginForm("Logout", "AccountEmpresa", FormMethod.Post, new { @class = "frmLogout", role = "form" }))
{
    <p class="text-center">¿Esta seguro que desea cerrar sesión?</p>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6 text-center">
                <button type="button" class="btn btn-red font-montserrat" data-dismiss="modal"><i class="fa fa-close" aria-hidden="true"></i>&nbsp;Cancelar</button>
            </div>
            <div class="col-sm-6 text-center">
                <button type="submit" class="btn btn-green font-montserrat btnCerrarSesion"><i class="" aria-hidden="true"></i>&nbsp;Aceptar</button>
            </div>
        </div>
    </div>
}